version: '3'

services:
  nginx:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
      args: ${DOMAIN_NAME}
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - wordpress-volume:/var/www/
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    image: mariadb
    container_name: mariadb
    expose:
      - "3306"
    networks:
      - inception
    restart: always
    volumes:
      - mariadb-volume:/var/lib/mysql  # Corrected volume mount path

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    image: wordpress
    container_name: wordpress
    expose:
      - "9000"
      - "3306"
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress-volume:/var/www/
    restart: always

volumes:
  wordpress-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  mariadb-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb
# bind - allows to mount dir.from the host machine into the container 
# none - default type (directory)

networks:
  inception:
    driver: bridge
# bridge - default network driver in Docker
